name: ci

on:
  push:

jobs:
  testgame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: make setup
      - name: Run phpunit
        run: make test
      - name: Run test script
        run: make run